backend:
  name: github
  repo: Cheng-222/Cheng-222.github.io
  branch: master
  # 注意：生产环境需配置 GitHub OAuth（回调地址）或使用 Netlify Git Gateway。

local_backend: true # 本地开发可选（需要运行本地代理服务）

publish_mode: simple
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: data
    label: 站点数据
    files:
      - file: "public/content/data.json"
        name: data
        label: 站点数据 JSON
        format: json
        fields:
          - label: 个人资料
            name: profile
            widget: object
            fields:
              - { label: 昵称, name: name, widget: string, required: false }
              - { label: 头衔, name: title, widget: string, required: false }
              - { label: 邮箱, name: email, widget: string, required: false }
              - { label: 微信, name: wechat, widget: string, required: false }
              - { label: 简介, name: intro, widget: text, required: false }
              - { label: 头像, name: avatar, widget: image, required: false }

          - label: 分类
            name: categories
            widget: list
            allow_add: true
            fields:
              - { label: 分类ID, name: id, widget: number }
              - { label: 名称, name: name, widget: string }
              - { label: 描述, name: description, widget: text, required: false }

          - label: 文章
            name: articles
            widget: list
            allow_add: true
            fields:
              - { label: ID, name: id, widget: number }
              - { label: 标题, name: title, widget: string }
              - { label: 发布时间, name: publishTime, widget: datetime, required: false }
              - { label: 分类ID, name: categoryId, widget: number }
              - { label: 摘要, name: excerpt, widget: text, required: false }
              - { label: 正文, name: content, widget: markdown, required: false }
              - { label: 封面图, name: cover, widget: image, required: false }
              - label: 标签
                name: tags
                widget: list
                field:
                  { label: 标签, name: tag, widget: string }
              - { label: 浏览量, name: views, widget: number, required: false }
              - { label: 评论数, name: comments, widget: number, required: false }
